---
- name: Create a Storage mapping
  hosts: localhost
  vars:
    provider_name: rhv-provider
    provider_namespace: openshift-mtv
    storage_map_name: rhv-storage-map

  #This vars can be passed from variables in AAP
  pre_tasks:
    - name: Log in to RHV
      ovirt.ovirt.ovirt_auth:
        hostname: "{{ rhv_api }}"
        username: "{{ rhv_user }}"
        password: "{{ rhv_password }}"
        insecure: true

  tasks:
    - name: Get info about Storage Domains
      ovirt.ovirt.ovirt_storage_domain_info:
        pattern: name=sd1 #<-- you can filter what VMs do you want to get filter by name, cluster, datacenter,SotrageDomain
        #                         (Search term which is accepted by oVirt/RHV search backend.)
        auth: "{{ ovirt_auth }}"
      register: storage_domains

    - name: Show registered variable
      ansible.builtin.debug:
        var: storage_domains

    - name: Register the storage domain
      ansible.builtin.set_fact:
        storage_domain_id: "{{ storage_domains.ovirt_storage_domains | map(attribute='id') | list }}"

    - name: Display Storage domain ID
      ansible.builtin.debug:
        var: storage_domain_id

    - name: Create or update a StorageMap
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: StorageMap
          metadata:
            name: "{{ storage_map_name }}"
            namespace: openshift-mtv
          spec:
            map:
              - destination:
                  storageClass: nfs-storage
                source:
                  id: "{{ storage_domain_id[0] }}"
            provider:
              destination:
                name: host
                namespace: openshift-mtv
              source:
                name: "{{ provider_name }}"
                namespace: openshift-mtv
