---
## MAKE sure you remove the Migration object migration-rhv-to-ocp before 
## otherwise this play won't work
## To remove it: oc delete -m openshift-mtv migration migration-rhv-to-ocp
- name: Get all VMs ID from RHV
  hosts: localhost
  vars:
    provider_name: rhv-provider
    provider_namespace: openshift-mtv
    plan_name: plan-from-ansible

  tasks:
    # Get the info about Storage Domains
    # - name:
    - name: Create the RHV provider
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            name: migration-rhv-to-ocp
            namespace: "{{ provider_namespace }}"
          spec:
            plan:
              name: "{{ plan_name }}"
              namespace: "{{ provider_namespace }}"
