---
- name: Get all VMs ID from RHV
  hosts: localhost

  #This info is passed from credential in AAP
  pre_tasks:
    - name: Log in to RHV
      ovirt.ovirt.ovirt_auth:
        hostname: "{{ rhv_api }}"
        username: "{{ rhv_user }}"
        password: "{{ rhv_password }}"
        insecure: true

  tasks:
    - name: Get VM information from RHV
      ovirt.ovirt.ovirt_vm_info:
        #pattern: cluster=MTV and Storage=sd1 <-- you can filter what VMs do you want to get filter by name, cluster, datacenter,SotrageDomain
        #                         (Search term which is accepted by oVirt/RHV search backend.)
        auth: "{{ ovirt_auth }}"
      register: rhv_vms
    
    - name: Show registered variable
      ansible.builtin.debug:
        var: rhv_vms 

    - name: Register all VM IDs
      ansible.builtin.set_fact:
        vm_ids: "{{ rhv_vms.ovirt_vms | map(attribute='name') | list }}"

    - name: Display VM IDs
      ansible.builtin.debug:
        var: vm_ids
    # Get the info about Storage Domains
    - name: