---
- name: Get all VMs ID from RHV
  hosts: localhost

  #This info is passed from credential in AAP
  pre_tasks:
    - name: Login to RHV
      ovirt.ovirt.ovirt_auth:
        hostname: "{{ rhv_api }}"
        username: "{{ rhv_user }}"
        password: "{{ rhv_password }}"
        insecure: true

  tasks:
    - name: Get VM information from RHV
      ovirt.ovirt.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
      register: rhv_vms

    - name: Register all VM IDs
      set_fact:
        vm_ids: "{{ rhv_vms.ovirt_vms | map(attribute='id') | list }}"

    - name: Display VM IDs
      debug:
        var: vm_ids