- name: Set up storageclasses in OCP 
  hosts: localhost
  vars:
    ansible_python_interpreter: auto

  tasks:
    - name: Login to OCP
      kubernetes.core.k8s_auth:
        username: admin
        host: https://api.ocp4.example.com:6443 
        password: redhatocp
        validate_certs: false
      register: k8s_auth_results

    - name: Show info
      debug:
        msg: "{{ k8s_auth_results }}"
    
    - name: Set fact for api key
      set_fact:
         token_api: "{{ k8s_auth_results.k8s_auth.api_key }}"

    - name: Get info Pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: all
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}" 
      register: pods



