---
# The command to get the concers for a given VM
# curl -H "Authorization: Bearer $TOKEN" https://forklift-inventory-namespace-domain/providers/ovirt/provider_id/workloads/vm_id | jq .concerns

- name: Show concerns from forklift MTV
  hosts: localhost
  vars:
    provider_name: rhv-provider
    token: sha256~HTVKcp8K8y665310bsCxI-2S636aCwuHBo_07W5w3NM # Obtain from oc whoami -t)
  tasks:

    - name: Get the UID of the rhv-provider
      ansible.builtin.uri:
        url: 'https://forklift-inventory-openshift-mtv.apps.ocp4.example.com/providers/ovirt'
        method: GET
        headers: 
          Authorization: "Bearer {{ token }}"
        validate_certs: false
      register: provider_uid

    - name: Show provider UID
      ansible.builtin.debug:
        msg: "{{ provider_uid.json[0].id }}"

    - name: Get the ID for all the VMs
      ansible.builtin.uri:
        url: "https://forklift-inventory-openshift-mtv.apps.ocp4.example.com/providers/ovirt/{{ provider_uid.json[0].id }}/vms"
        method: GET
        headers: 
          Authorization: "Bearer {{ token }}"
        validate_certs: false
      register: list_of_id_vm

    - name: Show VMs 
      ansible.builtin.debug:
        msg: "{{ list_of_id_vm.json | map(attribute='id') | list }}"

    - name: Get all the concerns for each VM
      ansible.builtin.uri:
        url: "https://forklift-inventory-openshift-mtv.apps.ocp4.example.com/providers/ovirt/{{ provider_uid.json[0].id }}/workloads/{{ item }}"
        method: GET
        headers: 
          Authorization: "Bearer {{ token }}"
        validate_certs: false
      loop: "{{ list_of_id_vm.json | map(attribute='id') }}"
      register: concerns 

    - name: Debug variable CONCERNS
      ansible.builtin.debug:
        msg: "{{ concerns.results[0].json.concerns  }}"

    - name: Initialize summary variable
      set_fact:
        summary: []

    - name: Update summary variable with task results
      set_fact:
        summary: "{{ summary + [ { 'vm_id': item, 'response': concerns.results[index0].json.concerns } ] }}"
      loop: "{{ list_of_id_vm.json | map(attribute='id') }}"
      loop_control:
        index_var: index0

    - name: Display summary
      debug:
        var: summary 