---
- name: Manage Kubernetes Storage Classes
  hosts: localhost
  gather_facts: false

  module_defaults:
    group/kubernetes.core.k8s:
      host: https://api.ocp4.example.com:6443
      validate_certs: false

  tasks:
    - name: Gather Kubernetes storage classes
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
      register: sc_facts

    - name: Create a fact list of all storage classes
      ansible.builtin.set_fact:
        storage_classes: "{{ sc_facts.resources }}"
    - name: debug variable
      ansible.builtin.debug:
        msg: "{{ storage_classes }}"

    - name: Initialize list variable
      ansible.builtin.set_fact:
        current_default_sc: []

    - name: Check for existing default storage class
      ansible.builtin.set_fact:
        current_default_sc: "{{ current_default_sc + [item.metadata.name] }}"
      loop: "{{ storage_classes }}"
      when:
        - item.metadata.annotations['storageclass.kubernetes.io/is-default-class'] is defined
        - item.metadata.annotations['storageclass.kubernetes.io/is-default-class']  == 'true'

    - name: Debug current_default_sc
      ansible.builtin.debug:
        msg: "{{ current_default_sc }}"

    - name: Evaluate if the play should end becasue cepth is the only storage class by default
      when: current_default_sc | length == 1 and current_default_sc[0] == "ocs-external-storagecluster-ceph-rbd"
      ansible.builtin.meta: end_play

    - name: Remove default from all other storage classes
      kubernetes.core.k8s:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: "{{ item.metadata.name }}"
        state: present
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "false"
      loop: "{{ storage_classes }}"

    - name: Set Ceph as the default storage class
      kubernetes.core.k8s:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: ocs-external-storagecluster-ceph-rbd
        state: present
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
