---
collections:
  - name: redhat.openshift
  - name: kubernetes.core
  - name: community.general
  - name: infra.aap_utilities
  - name: infra.controller_configuration
  - name: ansible.controller
  - name: community.crypto
  - name: ansible.posix
  - name: ovirt.ovirt
